version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hostel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hostel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_grace_period: 10s
    stop_signal: SIGINT
    networks:
     - hostel_network
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - hostel_network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - "OPENSEARCH_HOSTS=http://opensearch:9200"
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - hostel_network
    depends_on:
      - opensearch

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.local
    depends_on:
      db:
        condition: service_healthy
      opensearch:
        condition: service_started  # Добавьте эту зависимость
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - UPLOAD_DIR=/app/uploads
      - DATABASE_URL=postgres://postgres:password@db:5432/hostel_db?sslmode=disable
      - OPENSEARCH_URL=http://opensearch:9200  # Явно указываем URL для OpenSearch
      - OPENSEARCH_MARKETPLACE_INDEX=marketplace  # Указываем имя индекса
    stop_grace_period: 10s
    stop_signal: SIGTERM
    init: true
    networks:
      - hostel_network
  frontend:
    build:
      context: ./frontend/hostel-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/hostel-frontend/.env.local
    volumes:
      - ./frontend/hostel-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - hostel_network
  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:password@db:5432/hostel_db?sslmode=disable",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    stop_grace_period: 1s
    restart: "no"
    networks:
      - hostel_network
volumes:
  postgres_data:
  opensearch-data:

networks:
  hostel_network:
    driver: bridge