version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/hostel-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # React по умолчанию использует порт 3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WATCHPACK_POLLING=true  # Для hot-reload на Windows/WSL
    volumes:
      - ./frontend/hostel-frontend:/app
      - /app/node_modules
    command: ["npm", "start"]
    networks:
      - hostel_network

networks:
  hostel_network:
    driver: bridge