services:
  db:
    image: postgres:15
    container_name: hostel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hostel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_grace_period: 10s
    stop_signal: SIGINT
    networks:
     - hostel_network
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - hostel_network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - "OPENSEARCH_HOSTS=http://opensearch:9200"
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - hostel_network
    depends_on:
      - opensearch
  minio:
    image: minio/minio:RELEASE.2023-09-30T07-02-29Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: 1321321321321
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - hostel_network
    restart: unless-stopped
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin 1321321321321;
      /usr/bin/mc mb --ignore-existing myminio/listings;
      /usr/bin/mc policy set public myminio/listings;
      exit 0;
      "
    networks:
      - hostel_network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.local
    depends_on:
      db:
        condition: service_healthy
      opensearch:
        condition: service_started
    volumes:
      - ./backend/uploads:/app/uploads
      - minio_data:/app/minio-data
    environment:
      - APP_MODE=production
      - ENV_FILE=.env
      - WS_ENABLED=true
      - UPLOAD_DIR=/app/uploads
      - DATABASE_URL=postgres://postgres:password@db:5432/hostel_db?sslmode=disable
      - OPENSEARCH_URL=http://opensearch:9200
      - OPENSEARCH_MARKETPLACE_INDEX=marketplace
      - FILE_STORAGE_PROVIDER=minio
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=1321321321321
      - MINIO_USE_SSL=false
      - MINIO_BUCKET_NAME=listings
      - MINIO_LOCATION=eu-central-1
      - FILE_STORAGE_PUBLIC_URL=http://localhost:3000
    user: "101:101"
    stop_grace_period: 10s
    stop_signal: SIGTERM
    init: true
    networks:
      - hostel_network

  frontend:
    build:
      context: ./frontend/hostel-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/hostel-frontend/.env.local
    volumes:
      - ./frontend/hostel-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - hostel_network
  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:password@db:5432/hostel_db?sslmode=disable",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    stop_grace_period: 1s
    restart: "no"
    networks:
      - hostel_network
volumes:
  postgres_data:
  opensearch-data:
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/hostel-data/minio

networks:
  hostel_network:
    driver: bridge