version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/hostel-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - WDS_SOCKET_PORT=3001
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    volumes:
      - ./frontend/hostel-frontend:/app
      # Исключаем node_modules из монтирования
      - /app/node_modules
    networks:
      - hostel_network

networks:
  hostel_network:
    driver: bridge