version: '3.8'
services:
  db:
    image: postgres:15
    container_name: hostel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: c9XWc7Cm
      POSTGRES_DB: hostel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hostel_network
    stop_grace_period: 10s
    stop_signal: SIGINT

  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:c9XWc7Cm@db:5432/hostel_db?sslmode=disable",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hostel_network
    stop_grace_period: 1s
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - APP_MODE=production
      - ENV_FILE=.env
      - WS_ENABLED=true
    user: "101:101"
    volumes:
      - ./backend/uploads:/app/uploads
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - hostel_network
    stop_grace_period: 10s
    stop_signal: SIGTERM
    init: true

  nginx:
    image: nginx:alpine
    container_name: hostel_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/hostel-frontend/build:/usr/share/nginx/html:ro
      - ./backend/uploads:/usr/share/nginx/uploads:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - hostel_network
    stop_grace_period: 5s
    stop_signal: SIGTERM

volumes:
  postgres_data:

networks:
  hostel_network:
    driver: bridge