version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hostel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: c9XWc7Cm
      POSTGRES_DB: hostel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hostel_network

  backend:
    build: ./backend
    container_name: hostel_backend
    env_file:
        - ./backend/.env
    networks:
        - hostel_network
    environment:
      - DATABASE_URL=postgres://postgres:c9XWc7Cm@db:5432/hostel_db?sslmode=disable
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: hostel_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/hostel-frontend/build:/usr/share/nginx/html:ro
      - ./backend/uploads:/usr/share/nginx/uploads
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - hostel_network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: hostel_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - hostel_network

volumes:
  postgres_data:

networks:
  hostel_network:
    driver: bridge