services:
  db:
    image: postgres:15
    container_name: hostel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: c9XWc7Cm
      POSTGRES_DB: hostel_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hostel_network
    stop_grace_period: 10s
    stop_signal: SIGINT
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - hostel_network
    restart: unless-stopped
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.svetu.rs
    domainname: svetu.rs
    ports:
      - "25:25"      # SMTP
      - "587:587"    # SMTP с шифрованием
      - "465:465"    # SMTPS
      - "143:143"    # IMAP
      - "993:993"    # IMAPS
      - "110:110"    # POP3
      - "995:995"    # POP3S
    volumes:
      - ./mailserver/mail-data:/var/mail
      - ./mailserver/mail-state:/var/mail-state
      - ./mailserver/mail-logs:/var/log/mail
      - ./mailserver/config:/tmp/docker-mailserver
      - ./certbot/conf:/etc/letsencrypt
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_AMAVIS=1
      - POSTMASTER_ADDRESS=postmaster@svetu.rs
      - SSL_CERT_PATH=/etc/letsencrypt/live/svetu.rs/fullchain.pem
      - SSL_KEY_PATH=/etc/letsencrypt/live/svetu.rs/privkey.pem
    cap_add:
      - NET_ADMIN
    networks:
      - hostel_network
    restart: unless-stopped
#  opensearch-dashboards:
#    image: opensearchproject/opensearch-dashboards:2.11.0
#    container_name: opensearch-dashboards
#    ports:
#      - "5601:5601"
#    environment:
#      - "OPENSEARCH_HOSTS=http://opensearch:9200"
#      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
#    networks:
#      - hostel_network
#    depends_on:
#      - opensearch
#    restart: unless-stopped

  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:c9XWc7Cm@db:5432/hostel_db?sslmode=disable",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hostel_network
    stop_grace_period: 1s
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - APP_MODE=production
      - ENV_FILE=.env
      - WS_ENABLED=true
      - OPENSEARCH_URL=http://opensearch:9200
      - OPENSEARCH_MARKETPLACE_INDEX=marketplace
    user: "101:101"
    volumes:
      - uploads_data:/app/uploads
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      opensearch:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - hostel_network
    stop_grace_period: 10s
    stop_signal: SIGTERM
    init: true
    restart: unless-stopped

  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    container_name: hostel_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/hostel-frontend/build:/usr/share/nginx/html:ro
      - /opt/hostel-data/klimagrad-site:/usr/share/nginx/klimagrad-site:ro
      - uploads_data:/usr/share/nginx/uploads:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - hostel_network
    stop_grace_period: 5s
    stop_signal: SIGTERM
    restart: unless-stopped

volumes:
  db_data:
  opensearch_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/hostel-data/opensearch
  uploads_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/hostel-data/uploads

networks:
  hostel_network:
    driver: bridge