# Пример конфигурации Harbor для Sve Tu Platform

# Основные настройки
hostname: 207.180.197.172  # Замените на ваш домен, если есть
http:
  port: 80
https:
  port: 443
  # Пути к сертификатам (заполните при настройке HTTPS)
  # certificate: /your/certificate/path
  # private_key: /your/private/key/path

# Пароль для администратора
harbor_admin_password: SveTu2025  # Обязательно измените на надежный пароль

# Путь для хранения данных
data_volume: /data

# База данных
database:
  password: root123
  max_idle_conns: 100
  max_open_conns: 900

# Настройка режима хранения образов
storage_service:
  ca_bundle: /etc/harbor/ca-bundle.crt
  provider_name: filesystem
  filesystem:
    rootdirectory: /data

# Параметры очистки данных (garbage collection)
jobservice:
  max_job_workers: 10

# Настройки журналов
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

# Настройка уведомлений
notification:
  webhook_job_max_retry: 10

# Настройки трассировки
trace:
  enabled: false

# Сервисы, которые будут установлены
trivy:
  ignore_unfixed: false
  skip_update: false
  insecure: false
  
# Настройки прокси-сервера (если нужно)
# proxy:
#   http_proxy: 
#   https_proxy: 
#   no_proxy: 127.0.0.1,localhost

# Настройки для отправки метрик
metric:
  enabled: false
  port: 9090
  path: /metrics

# Включите эту секцию, если нужно настроить TLS
# internal_tls:
#   enabled: false